"""user_detail model added

Revision ID: 5a5b3e538734
Revises: 79ed9538a4ad
Create Date: 2018-12-11 16:24:25.932210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5b3e538734'
down_revision = '79ed9538a4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('datetime', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_details_image_url'), 'users_details', ['image_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_details_image_url'), table_name='users_details')
    op.drop_table('users_details')
    # ### end Alembic commands ###
